# # This file should contain all the record creation needed to seed the database with its default values.
# # The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
# #
# # Examples:
# #
# #   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
# #   Mayor.create(name: 'Emanuel', city: cities.first)
#
Group.create!(name: "Inner City Basketball")
Group.create!(name: "Uptown Tennis League")
Group.create!(name: "Rugby for Foreigners")
Group.create!(name: "Baseball in the Suburbs")
Group.create!(name: "Hipster Soccer")
Group.create!(name: "Nerd Chess")
Group.create!(name: "Running with Scissors")

User.create!(email: "bob@bob.com", password: "testing!", full_name: "Bob")
User.create!(email: "steve@steve.com", password: "testing!", full_name: "Steve")
User.create!(email: "ted@ted.com", password: "testing!", full_name: "Ted")
User.create!(email: "will@will.com", password: "testing!", full_name: "Will")
User.create!(email: "karen@karen.com", password: "testing!", full_name: "Karen")
User.create!(email: "sue@sue.com", password: "testing!", full_name: "Sue")
User.create!(email: "wanda@wanda.com", password: "testing!", full_name: "Wanda")
User.create!(email: "tabatha@tabatha.com", password: "testing!", full_name: "Tabatha")
User.create!(email: "lucas@lucas.com", password: "testing!", full_name: "Lucas")
User.create!(email: "maurice@maurice.com", password: "testing!", full_name: "Maurice")

Membership.create!(group_id: 1 , user_id: 1, access_level: "admin" )
Membership.create!(group_id: 1 , user_id: 2, access_level: "member" )
Membership.create!(group_id: 1 , user_id: 3, access_level: "member" )
Membership.create!(group_id: 2 , user_id: 4, access_level: "admin" )
Membership.create!(group_id: 2 , user_id: 5, access_level: "member" )
Membership.create!(group_id: 2 , user_id: 6, access_level: "member" )
Membership.create!(group_id: 3 , user_id: 7, access_level: "admin" )
Membership.create!(group_id: 3 , user_id: 8, access_level: "member" )
Membership.create!(group_id: 4 , user_id: 9, access_level: "admin" )
Membership.create!(group_id: 4 , user_id: 10, access_level: "admin" )
Membership.create!(group_id: 4 , user_id: 1, access_level: "member" )
Membership.create!(group_id: 4 , user_id: 2, access_level: "member" )
Membership.create!(group_id: 5 , user_id: 3, access_level: "admin" )
Membership.create!(group_id: 5 , user_id: 4, access_level: "admin" )
Membership.create!(group_id: 5 , user_id: 5, access_level: "admin" )
Membership.create!(group_id: 5 , user_id: 6, access_level: "member" )
Membership.create!(group_id: 5 , user_id: 7, access_level: "member" )
Membership.create!(group_id: 5 , user_id: 8, access_level: "member" )
Membership.create!(group_id: 5 , user_id: 9, access_level: "member" )
Membership.create!(group_id: 5 , user_id: 10, access_level: "member" )
Membership.create!(group_id: 6 , user_id: 5, access_level: "admin" )
Membership.create!(group_id: 6 , user_id: 6, access_level: "member" )
Membership.create!(group_id: 6 , user_id: 7, access_level: "member" )
Membership.create!(group_id: 6 , user_id: 8, access_level: "member" )
Membership.create!(group_id: 7 , user_id: 9, access_level: "admin" )

Article.create!(group_id: 1)
Article.create!(group_id: 2)
Article.create!(group_id: 4)
Article.create!(group_id: 4)
Article.create!(group_id: 3)
Article.create!(group_id: 5)

Version.create!(article_id: 1, author_id: 3, title: "Basketball Rules" , body: "Here is the final version..." , privacy_level: "private" )
Version.create!(article_id: 1, author_id: 2, title: "Basketball *Rules*", body: "Another Draft...", privacy_level: "private" )
Version.create!(article_id: 1, author_id: 2, title: "B-ball Rules", body: "Another Draft...", privacy_level: "private" )
Version.create!(article_id: 1, author_id: 1, title: "Basketball Rules", body: "Another Draft...", privacy_level: "private" )
User.find(4).versions.create(article_id: 2, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "public" )
User.find(5).versions.create(article_id: 2, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "public" )
User.find(5).versions.create(article_id: 2, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "public" )
User.find(6).versions.create(article_id: 2, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "public" )
User.find(9).versions.create(article_id: 3, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private" )
User.find(10).versions.create(article_id: 3, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private" )
User.find(1).versions.create(article_id: 3, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private" )
User.find(2).versions.create(article_id: 4, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private" )
User.find(1).versions.create(article_id: 4, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private" )
User.find(1).versions.create(article_id: 4, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private" )
User.find(2).versions.create(article_id: 4, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private" )
Article.find(5).versions.create!(author_id: 7, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private")
Article.find(5).versions.create!(author_id: 8, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private")
Article.find(6).versions.create!(author_id: 4, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private")
Article.find(6).versions.create!(author_id: 4, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private")
Article.find(6).versions.create!(author_id: 5, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private")
Article.find(6).versions.create!(author_id: 5, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private")
Article.find(6).versions.create!(author_id: 6, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private")
Article.find(6).versions.create!(author_id: 7, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private")
Article.find(6).versions.create!(author_id: 9, title: Faker::Book.title, body: Faker::Lorem.paragraphs(6).join("\n"), privacy_level: "private")


Article.create!(group_id: 1).versions.create!(title: "Rules and Regulations", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 1).versions.create!(title: "Our Constitution", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 1).versions.create!(title: "Other Rules", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 1).versions.create!(title: "Weekly Schedule", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 2).versions.create!(title: "Yet another Rulesheet", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 2).versions.create!(title: "Super Bowl!", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 2).versions.create!(title: "Lucas the Client is Awesome!", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 2).versions.create!(title: "Maurice Lays Down the Law", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 3).versions.create!(title: "Tips and Tricks", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 3).versions.create!(title: "Thoughts", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 3).versions.create!(title: "Incident", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 3).versions.create!(title: "Another Problem", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 4).versions.create!(title: "Meetup", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 4).versions.create!(title: "Party", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 4).versions.create!(title: "Secret Buddies", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 4).versions.create!(title: "Favorite Foods", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 5).versions.create!(title: "Heads Up!", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 5).versions.create!(title: "How to Get Better", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 5).versions.create!(title: "Ways to Win", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 5).versions.create!(title: "Our Tournament", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 6).versions.create!(title: "Postseason", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 6).versions.create!(title: "My Epiphany", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 6).versions.create!(title: "Team Captains", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 6).versions.create!(title: "Overseas Trip", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 7).versions.create!(title: "Last Week", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 7).versions.create!(title: "Changes to Schedule", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 7).versions.create!(title: "Even More Problems", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 7).versions.create!(title: "This is Cool", body: Faker::Lorem.paragraphs(6).join("\n"))

Article.create!(group_id: 3).versions.create!(title: "Lucas the Client is Awesome", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 3).versions.create!(title: "Everybody Loves Maurice", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 3).versions.create!(title: "This is Great!", body: Faker::Lorem.paragraphs(6).join("\n"))

Article.create!(group_id: 1).versions.create!(title: "Sweet Moves!", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 1).versions.create!(title: "Who Can Dunk?", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 1).versions.create!(title: "Your Feedback Needed", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 2).versions.create!(title: "Another Idea", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 2).versions.create!(title: "End of Season Party?", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 2).versions.create!(title: "We Have a Thief", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 3).versions.create!(title: "Captains' Meeting", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 3).versions.create!(title: "Interesting Experiment", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 3).versions.create!(title: "Car Crash", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 4).versions.create!(title: "Favorite Movie", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 4).versions.create!(title: "Bring Your Own Towel", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 4).versions.create!(title: "This is Strange", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 5).versions.create!(title: "The Best", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 5).versions.create!(title: "Another Person", body: Faker::Lorem.paragraphs(6).join("\n"))
Article.create!(group_id: 5).versions.create!(title: "It's Strange", body: Faker::Lorem.paragraphs(6).join("\n"))
